version: '3.8'
services:
  ems:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: QRAXTm109!
      MYSQL_DATABASE: employee  
    volumes:
      - mysql-data:/var/lib/mysql   

volumes:        
  mysql-data:

